# Generated by Django 5.1.4 on 2024-12-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_mydetails_file_mydetails_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydetails',
            name='image',
        ),
        migrations.AddField(
            model_name='mydetails',
            name='file',
            field=models.FileField(default=1, upload_to='Mydetails/'),
            preserve_default=False,
        ),
    ]
